[build]
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  # Redirect API calls to Netlify Functions
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

  from = "/api/signup"
  to = "/.netlify/functions/signup"
  status = 200

  # Redirect all other API calls
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
